############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1

[[main]]
name = "Giới thiệu"
pageRef = "/about"
weight = 2

[[main]]
name = "Lĩnh vực hoạt động"
weight = 3

[[main]]
parent = "Lĩnh vực hoạt động"
name = "Tư vấn luật"
pageRef = "/legal-consulting"
weight = 1

[[main]]
parent = "Lĩnh vực hoạt động"
name = "Tham gia tố tụng"
pageRef = "/litigation-service"
weight = 2

[[main]]
parent = "Lĩnh vực hoạt động"
name = "Dịch vụ pháp lý"
pageRef = "/legal-service"
weight = 3

[[main]]
weight = 4
name = "Xem thêm"

[[main]]
parent = "Xem thêm"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Xem thêm"
name = "Liên hệ"
pageRef = "/contact"



# footer menu
[[footer]]
name = "Giới thiệu"
pageRef = "/about"
weight = 1

[[footer]]
name = "Liên hệ"
pageRef = "/contact"
weight = 2

[[footer]]
name = "Bảo mật"
pageRef = "/privacy-policy"
weight = 3
