############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1

[[main]]
name = "Giới thiệu"
pageRef = "/about"
weight = 2

[[main]]
name = "Dịch vụ"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "Xem thêm"

[[main]]
parent = "Xem thêm"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Xem thêm"
name = "Liên hệ"
pageRef = "/contact"



# footer menu
[[footer]]
name = "Giới thiệu"
pageRef = "/about"
weight = 1

[[footer]]
name = "Dịch vụ"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Bảo mật"
pageRef = "/privacy-policy"
weight = 3
