############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Services"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "More"

[[main]]
parent = "More"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "More"
name = "Contact"
pageRef = "/contact"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
